[package]
name = "console_engine"
description = "A simple console framework that provides display and keyboard features"
version = "0.4.1"
authors = ["Vincent Foulon <sup.vfoulon@gmail.com>"]
repository = "https://github.com/VincentFoulon80/console_engine"
readme = "README.md"
keywords = ["terminal","tui", "input"]
license = "MIT"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = "1.5.5"
# for windows support, uncomment this :
# termion = { git = "https://gitlab.redox-os.org/Jezza/termion", branch = "windows-support", package = "termion"}


[dev-dependencies]
rand = "0.7.3"
